apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::006315788103:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-LBNT1441OZXY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::006315788103:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-14T23:31:03Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-03-14T23:31:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-patch
    operation: Update
    time: "2021-03-14T23:39:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2949"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0a7129f0-8c1f-4584-914b-904e9309f476